# Task 5: Simple Batch Normalization and Layer Normalization

Understand the exact difference between Batch Normalization (across samples) and Layer Normalization (across features).

In [1]:
import torch

### 1. Create Input Batch (3 samples, 4 features)

In [4]:
X = torch.tensor([
    [10.0, 20.0, 30.0, 40.0],
    [ 2.0,  4.0,  6.0,  8.0],
    [50.0, 60.0, 70.0, 80.0]
])
print('Original Input X:\n', X)

Original Input X:
 tensor([[10., 20., 30., 40.],
        [ 2.,  4.,  6.,  8.],
        [50., 60., 70., 80.]])


### 2. Batch Normalization (Normalizes COLUMNS across batch)

In [5]:
# Column-wise mean and variance
bn_mean = X.mean(dim=0)
bn_var = X.var(dim=0, unbiased=False)
X_bn = (X - bn_mean) / torch.sqrt(bn_var + 1e-5)

print('\nBatch Normalized X (Column Mean = 0, Std = 1):\n', X_bn.round(decimals=2))


Batch Normalized X (Column Mean = 0, Std = 1):
 tensor([[-0.5100, -0.3400, -0.2000, -0.0900],
        [-0.8900, -1.0200, -1.1100, -1.1800],
        [ 1.4000,  1.3600,  1.3100,  1.2700]])


### 3. Layer Normalization (Normalizes ROWS across features)

In [6]:
# Row-wise mean and variance
ln_mean = X.mean(dim=1, keepdim=True)
ln_var = X.var(dim=1, keepdim=True, unbiased=False)
X_ln = (X - ln_mean) / torch.sqrt(ln_var + 1e-5)

print('\nLayer Normalized X (Row Mean = 0, Std = 1):\n', X_ln.round(decimals=2))


Layer Normalized X (Row Mean = 0, Std = 1):
 tensor([[-1.3400, -0.4500,  0.4500,  1.3400],
        [-1.3400, -0.4500,  0.4500,  1.3400],
        [-1.3400, -0.4500,  0.4500,  1.3400]])
